# logging options
save_dir: logs
project: MSI
name: debug

# task definition
data_config: data_config.yaml
task: binary
target: TARGET
num_classes: 1
cohorts: ["CRC"]
ext_cohorts: ["CRC"]
clini_info: {}
seed: null
label_dict:
  MSS: 0
  MSI: 1

# model options
model: Transformer
model_config:
  heads: 8
  dim_head: 64
  dim: 512
  mlp_dim: 512
norm: raw
feats: ctranspath
input_dim: 768
num_tiles: -1
pad_tiles: false

# training options
folds: 5
num_epochs: 8
criterion: BCEWithLogitsLoss
optimizer: AdamW
lr_scheduler: null
lr_scheduler_config: null
lr: 2.0e-05
wd: 2.0e-05
bs: 1
stop_criterion: loss
val_check_interval: 500
num_samples: null

