CRC:
  clini_table: ./clini_table.xlsx
  slide_csv: ./slides_all_per_patient.csv
  feature_dir:
    raw:
      ctranspath: ./h5_embeddings_per_patient  # in ['ctranspath', 'retccl']
  folds: ./h5_embeddings_per_patient/folds  # if it doesn't exist yet, it will be created automatically
